---
title: "rdantic"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rdantic}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rdantic)
library(rlang)
```

## Models

```{r}
person_model <- base_model(
  name = is_scalar_character,
  age = is_scalar_integer
)

person_model(
  name = "Lee",
  age = 100L
)

try(person_model(name = "Lee", age = 100))

# It is also possible to pass lists:
external_data <- list(name = "Morgan", age = 100L)

person_model(external_data)
```

## Validators

```{r}
person_model <- base_model(
  name = is_scalar_character,
  age = is_scalar_integer,
  .validators_before = list(
    age = as.integer
  )
)

person_model(name = "Lee", age = 100)
```

## Models inside models

```{r}
address_model <- base_model(
  city = is_scalar_character,
  country = is_scalar_character
)

person_model <- base_model(
  name = is_scalar_character,
  age = is_scalar_integer,
  address = is_another_model(address_model)
)

person_model(
  name = "Peter",
  age = 12L,
  address = address_model(city = "Kassel", country = "Germany")
)

external_data <- list(
  statusCode = 200L,
  data = list(
    value = 10,
    createdAt = "2024-08-12 20:20:05"
  )
)

data_model <- base_model(
  value = is_scalar_double,
  created_at = is_scalar_character,
  .validators_after = list(
    created_at = as.POSIXct
  )
)

api_model <- base_model(
  status_code = is_scalar_integer,
  data = is_another_model(data_model)
)

external_data |>
  keys_to_snake_case() |>
  api_model()
```
## Type safety of function arguments

```{r}
add_two_numbers <- function(a, b) {
  validate_args(a = is_scalar_double, b = is_scalar_double)
  a + b
}

add_two_numbers(10, 20)

try(add_two_numbers(10, c(20, 30)))
```

It also possible to add the type checks in this way:

```{r}
add_two_numbers <- function(a = is_scalar_integer, 
                            b = is_scalar_integer) {
  validate_fn(add_two_numbers)
  a + b
}

add_two_numbers(1L, 3L)

try(add_two_numbers(1L, 4.6))
```

## Settings

```{r}
Sys.setenv(POSTGRES_USERNAME = "postgres")
Sys.setenv(POSTGRES_PASSWORD = "superSecret!")
Sys.setenv(POSTGRES_PORT = 15432)

postgres_settings <- base_settings(
  username = as.character,
  password = as.character,
  port = as.integer,
  .prefix = "POSTGRES"
)

postgres_settings()

Sys.setenv(POSTGRES_PORT = "")

try(postgres_settings())
```
